<?php
$str = <<<JSON
{
    "code": 0,
    "msg": "success",
    "info": {
        "id": 2987131,
        "customer_id": 237,
        "trans_event_id": 2987131,
        "warehouse_id": 519,
        "driver_id": 2003420,
        "sales_id": 1000094,
        "bid_mgr_id": 1000090,
        "dd_id": 1000124,
        "car_id": 1,
        "work_time": "2017-09-06 10:00:00",
        "created_at": "2017-08-08 00:07:50",
        "updated_at": "2017-09-06 14:13:41",
        "check_in_time": "2017-09-06 14:12:41",
        "status": 900,
        "is_complete": 1,
        "complete_time": "2017-09-06 14:13:42",
        "exception_id": 0,
        "comment": "23234324",
        "is_supplement": 1,
        "is_auto_departure": 0,
        "sop_mgr_id": 1000232,
        "is_del": 0,
        "departure_time": "",
        "is_departure": 0,
        "event_type": 100,
        "type": 100,
        "inspect_status": 100,
        "inspect_at": "2017-09-06 14:13:41",
        "cargo_insurance_rate": 0,
        "day_off_refund_rate": 0,
        "have_sop": 1,
        "fcc_id": 0,
        "sop_rate": 0.08,
        "sop_royalty_rate": 0,
        "invoice_tax_rate": 0.06,
        "official_carriage_charge_id": 0,
        "invoice_contents": "货物运输代理服务费",
        "first_pay_money": 0,
        "trans_task_id": 14510,
        "task_type": 200,
        "task_line_name": "滴滴答11",
        "task_work_begin_time": "10:00:00",
        "task_work_end_time": "12:45:00",
        "task_is_back": 0,
        "is_addition": 0,
        "source_event_id": 0,
        "addition_count": 1,
        "addition_comment": "",
        "addition_seq": 0,
        "car_num": "京A23245",
        "car_team_id": 0,
        "adc_id": 1,
        "new_trade_level_one": 1,
        "new_trade_level_two": [
            3
        ],
        "have_temp_ctrl": 0,
        "inspect_reason": "",
        "project_type": 1,
        "bu_leader_id": 1000241,
        "insurance_begun_at": "2017-02-07 18:24:08",
        "bonus_money": 0,
        "subsidies": [
            {
                "subsidy_id": 0,
                "subsidy_name": "管理费",
                "type": 600,
                "subsidy_to": 100,
                "use_latest": true,
                "subsidy_mode": 100,
                "subsidy_sp": 0.12,
                "subsidy_money": -3600,
                "dprice": -3600,
                "cprice": 0,
                "comment": "",
                "cprice_display": 0,
                "dprice_display": -36
            },
            {
                "subsidy_id": 0,
                "subsidy_name": "奖励",
                "type": 500,
                "subsidy_to": 100,
                "use_latest": true,
                "subsidy_mode": 100,
                "subsidy_sp": 0.1,
                "subsidy_money": 3000,
                "dprice": 3000,
                "cprice": 0,
                "comment": "",
                "cprice_display": 0,
                "dprice_display": 30
            }
        ],
        "task_onboard_date": "2016-01-29",
        "select_driver_time": "2016-01-28 15:30:00",
        "task_type_display": "主司机",
        "status_display": "配送完成",
        "event_type_display": "普通运力",
        "inspect_status_display": "无",
        "first_pay_money_display": "周付款",
        "total_bonus_money": 0,
        "total_bonus_tax": 0,
        "extra_distribution_point_count": 0,
        "subsidies_display": "奖励(30元)",
        "commission_rate": 0.12,
        "subsidies_to_customer_display": "",
        "subsidies_to_driver_display": "奖励(30元)",
        "cprice_total_with_tax": 34344,
        "day_off_refund_price": 0,
        "day_off_charge_rate": 1,
        "day_off_refund_price_display": 0,
        "distribution_point_count": 0,
        "final_distribution_point_count": 0,
        "bonus_status": 300,
        "confirmed_at": "2017-09-07 15:00:02",
        "finance_pay_type": 100,
        "first_onboard_rate": 0,
        "trans_driver_bid_id": 10529,
        "driver_insurance_money": 399,
        "dprice_per_day": 30000,
        "dprice_subsidy_total": 3000,
        "cprice_per_day": 30000,
        "cprice_per_day_tax": 1800,
        "cprice_subsidy_total": 0,
        "cprice_total": 32400,
        "sop_price": 2400,
        "sop_price_tax": 144,
        "sop_royalty_price": 0,
        "first_onboard_price": 0,
        "cargo_insurance_price": 0,
        "cargo_insurance_price_tax": 0,
        "total_commission_money": -3600,
        "dprice_total": 29001,
        "total_bonus_with_tax": 0,
        "cargo_insurance_price_with_tax": 0,
        "sop_price_with_tax": 2544,
        "commission_money": -3600,
        "customer_bonus_charge": 0,
        "customer_bonus_charge_tax": 0,
        "bonus_sop_charge": 0,
        "bonus_sop_charge_tax": 0,
        "driver_bonus_money": 0,
        "bonus_commission_money": 0,
        "bonus_rewards_money": 0,
        "sop_royalty_for_bonus": 0,
        "temp_ctrl_price": 0,
        "temp_ctrl_price_tax": 0,
        "cprice_per_day_with_tax_display": 318,
        "temp_ctrl_price_display": 0,
        "temp_ctrl_price_tax_display": 0,
        "customer_bonus_charge_display": 0,
        "customer_bonus_charge_tax_display": 0,
        "bonus_sop_charge_display": 0,
        "bonus_sop_charge_tax_display": 0,
        "driver_bonus_money_display": 0,
        "bonus_commission_money_display": 0,
        "bonus_rewards_money_display": 0,
        "driver_insurance_money_display": "3.99",
        "sop_royalty_for_bonus_display": 0,
        "bonus_money_display": 0,
        "total_bonus_money_display": 0,
        "total_bonus_tax_display": 0,
        "sop_royalty_rate_display": "0%",
        "dprice_per_day_display": "300.00",
        "dprice_subsidy_total_display": 30,
        "cprice_per_day_display": "300.00",
        "cprice_per_day_tax_display": "18.00",
        "cprice_subsidy_total_display": 0,
        "cprice_total_display": "324.00",
        "cprice_total_with_tax_display": "343.44",
        "sop_price_display": "24.00",
        "sop_price_tax_display": "1.44",
        "sop_royalty_price_display": 0,
        "first_onboard_price_display": 0,
        "cargo_insurance_price_display": 0,
        "cargo_insurance_price_tax_display": 0,
        "total_commission_money_display": -36,
        "dprice_total_display": 290.01,
        "total_bonus_with_tax_display": 0,
        "cargo_insurance_price_with_tax_display": 0,
        "sop_price_with_tax_display": 25.44,
        "commission_money_display": -36,
        "task": {
            "id": 14510,
            "version": 1,
            "customer_id": 237,
            "type": 200,
            "status": 6000,
            "substatus": 2000,
            "open_task_time": "2016-01-28 14:43:27",
            "created_at": "2016-01-28 14:43:27",
            "updated_at": "2017-05-02 16:34:01",
            "task_info": {
                "warehouse_id": 519,
                "line_name": "滴滴答11",
                "driver_id": 2003420,
                "customer_price": 30000,
                "driver_price": 30000,
                "driver_info": {
                    "car_num": "京A23245",
                    "car_type_id": 1,
                    "select_driver_time": "2016-01-28 15:30:00"
                },
                "schedule": "FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU",
                "work_begin_time": "10:00:00",
                "time_cost": 9900,
                "onboard_date": "2016-01-29",
                "end_date": "2200-12-12",
                "expected_end_date": "2200-12-12",
                "is_distribution_point_fixed": null,
                "distribution_point_min": 1,
                "distribution_point_max": 2,
                "distribution_area": "32423432434",
                "distance_min": 11,
                "distance_max": 12,
                "is_back": 0,
                "scene": 100,
                "match_type": 100,
                "is_ignore_restrict": 1,
                "is_need_receipt": 0,
                "receipt_type": 0,
                "receipt_info": [],
                "expected_price_min": 0,
                "expected_price_max": 0,
                "expected_price_describe": "",
                "driver_welfare": {
                    "items": [],
                    "other": ""
                },
                "comment": "",
                "cargo_type": "33213",
                "cargo_volume_min": 11,
                "cargo_volume_max": 11,
                "cargo_weight_min": 11,
                "cargo_weight_max": 11,
                "cargo_number_min": 11,
                "cargo_number_max": 11,
                "distribution_points": null,
                "bonus_info": null
            },
            "requirement": {
                "trans_task_id": 14510,
                "city_id": [
                    1
                ],
                "car_type_id": [
                    1,
                    2,
                    6,
                    1032
                ],
                "deliver_experience": [
                    "305"
                ],
                "handling_type": 1,
                "other_handling_req": "",
                "is_req_xiaogong": 0,
                "is_with_load": 0,
                "is_with_unload": 0,
                "is_with_board": 0,
                "is_need_clear_seats": 1,
                "is_need_tuiche": 1,
                "is_limit_phone": 0,
                "is_ignore_restrict": 1,
                "is_need_practice_before_onboard": 0,
                "traffic_control_rule": null,
                "driver_req": "",
                "other_desc": {
                    "items": [
                        5,
                        6
                    ],
                    "other": ""
                },
                "extra": {
                    "receiving_bid_end_time": "2016-01-28 14:55:39",
                    "evaluating_bid_end_time": "2016-01-28 15:30:00"
                },
                "dispatch_end_time": null,
                "created_at": "2016-01-28 14:43:27",
                "updated_at": "2017-05-02 16:34:01"
            },
            "task_scope": null,
            "task_contract_config": null,
            "create_task_ip": "192.168.200.101",
            "is_delete": false,
            "customer_tcsp": 0,
            "invoice_tax_rate": 0.06,
            "sop_spp": 0.08,
            "bid_mgr_id": 1000090,
            "sales_id": 1000094,
            "customer_city_id": 1,
            "adc_id": 1,
            "warehouse_district": "朝阳区",
            "warehouse_city_id": 1,
            "job_process_status": 6000,
            "new_status": 2,
            "fcc_id": 0,
            "sop_mgr_id": 1000232,
            "dd_id": 1000124,
            "car_team_id": 0,
            "source": 301,
            "select_source": 301,
            "receiving_bid_end_time": "2016-01-28 14:55:39",
            "evaluating_bid_end_time": "2016-01-28 15:30:00",
            "match_type": 100,
            "scene": 100,
            "car_id": [
                1,
                2,
                6,
                1032
            ],
            "warehouse_id": 519,
            "line_name": "滴滴答11",
            "bid_driver_id": 2003420,
            "onboard_date": "2016-01-29",
            "work_begin_time": "10:00",
            "dispatch_end_time": null,
            "bonus_money": 0,
            "distribution_point_startup_count": 0,
            "driver_id": 2003420,
            "current_bid_id": 10529,
            "task_official_carriage_charge_id": 0,
            "trans_customer_subsidy_percentage": 0,
            "backup_bid_mgr_id": 0,
            "status_display": "选到可用司机",
            "current_bid_current_status": 2000,
            "project_id": null,
            "is_del": 0,
            "schedule": "FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU",
            "car_memo": "",
            "work_end_time": "12:45",
            "distribution_point_min": 1,
            "distribution_point_max": 2,
            "is_distribution_point_fixed": null,
            "distribution_area": "32423432434",
            "distribution_direct": "",
            "distance_min": 11,
            "distance_max": 12,
            "is_back": 0,
            "is_ignore_restrict": 1,
            "end_date": "2200-12-12",
            "cargo_type": "33213",
            "cargo_volume_min": 11,
            "cargo_volume_max": 11,
            "cargo_weight_min": 11,
            "cargo_weight_max": 11,
            "is_need_receipt": 0,
            "receipt_type": 0,
            "receipt_sendee": null,
            "receipt_describe": null,
            "receipt_express_fee_payer": 0,
            "expected_price_min": 0,
            "expected_price_max": 0,
            "expected_price_describe": "",
            "receipt_contacts": null,
            "receipt_address": "",
            "deliver_experience": "[\"305\"]",
            "reason": null,
            "handling_type": "1",
            "is_req_xiaogong": 0,
            "is_with_load": 0,
            "is_with_unload": 0,
            "is_with_board": 0,
            "other_handling_req": "",
            "is_need_clear_seats": 1,
            "is_need_tuiche": 1,
            "is_limit_phone": 0,
            "is_need_double_fire_extinguisher": null,
            "is_need_lock": null,
            "is_need_practice_before_onboard": 0,
            "driver_req": "",
            "other_desc": "{\"collect_money_by_pos_exp\":\"\\u9700\\u8981\",\"collect_cash_exp\":\"\\u9700\\u8981\"}",
            "traffic_control_rule": null,
            "comment": "",
            "cargo_number_min": 11,
            "cargo_number_max": 11,
            "cars_id": [
                1,
                2,
                6,
                1032
            ],
            "cities_id": [
                1
            ],
            "distribution_point_count": 0,
            "bonus_money_display": "0",
            "type_display": "主司机",
            "handling_type_display": "无需搬运",
            "schedule_display": [
                1,
                2,
                3,
                4,
                5,
                6,
                7
            ],
            "deliver_experience_display": {
                "305": "无要求"
            },
            "other_desc_display": {
                "collect_money_by_pos_exp": "需要",
                "collect_cash_exp": "需要"
            },
            "expected_price_min_display": 0,
            "expected_price_max_display": 0,
            "distribution_points": [],
            "mathch_one_level_status_display": "选到可用司机",
            "probation_start": "",
            "probation_end": "",
            "task_duration_days": 0,
            "select_driver_time": "2016-01-28 15:30:00",
            "task_scope.type": null,
            "task_scope.value": null,
            "time_cost": 9900,
            "driver_price": 30000
        },
        "bonus_commissinon_money": 0,
        "confirm_type": 200,
        "first_check_in": 0,
        "is_bonus_charged": 0,
        "is_first_onboard_bid": 0,
        "is_wrong_location": 0,
        "task_schedule": "FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR,SA,SU",
        "task_warehouse_id": 519,
        "distribution_point_max": 2,
        "distribution_min": 1,
        "bonux_sop_charge_tax_display": 0
    }
}
JSON;
var_export(json_decode($str,true));
